//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThyBilet.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ThyBiletEntities : DbContext
    {
        public ThyBiletEntities()
            : base("name=ThyBiletEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TBL_Birim> TBL_Birim { get; set; }
        public virtual DbSet<TBL_Departman> TBL_Departman { get; set; }
        public virtual DbSet<TBL_Durum> TBL_Durum { get; set; }
        public virtual DbSet<TBL_Gorev> TBL_Gorev { get; set; }
        public virtual DbSet<TBL_Kasa> TBL_Kasa { get; set; }
        public virtual DbSet<TBL_Musteri> TBL_Musteri { get; set; }
        public virtual DbSet<TBL_Personel> TBL_Personel { get; set; }
        public virtual DbSet<TBL_Ulke> TBL_Ulke { get; set; }
        public virtual DbSet<TBL_Telefon> TBL_Telefon { get; set; }
        public virtual DbSet<ilceler> ilceler { get; set; }
        public virtual DbSet<iller> iller { get; set; }
        public virtual DbSet<TBL_Class> TBL_Class { get; set; }
        public virtual DbSet<TBL_UcusUrun> TBL_UcusUrun { get; set; }
        public virtual DbSet<TBL_UcusUrunGrup> TBL_UcusUrunGrup { get; set; }
        public virtual DbSet<TBL_UrunGirdiCikti> TBL_UrunGirdiCikti { get; set; }
        public virtual DbSet<TBL_PersonelLogları> TBL_PersonelLogları { get; set; }
        public virtual DbSet<TBL_MusteriLogları> TBL_MusteriLogları { get; set; }
        public virtual DbSet<TBL_Koltuk> TBL_Koltuk { get; set; }
        public virtual DbSet<TBL_Ucus> TBL_Ucus { get; set; }
    }
}
