//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThyBilet.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_Musteri
    {
        public int MusteriID { get; set; }
        public string TC { get; set; }
        public string Mail { get; set; }
        public string Telefon { get; set; }
        public Nullable<int> Ulke { get; set; }
        public Nullable<int> Durum { get; set; }
        public string AdSoyad { get; set; }
        public string Adress { get; set; }
        public Nullable<int> Sehir { get; set; }
        public Nullable<int> ilce { get; set; }
        public string Sifre { get; set; }
        public Nullable<int> Ucus { get; set; }
        public Nullable<int> Koltuk { get; set; }
    
        public virtual TBL_Durum TBL_Durum { get; set; }
        public virtual ilceler ilceler { get; set; }
        public virtual iller iller { get; set; }
        public virtual TBL_Koltuk TBL_Koltuk { get; set; }
        public virtual TBL_Ucus TBL_Ucus { get; set; }
    }
}
