//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThyBilet.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_Koltuk
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBL_Koltuk()
        {
            this.TBL_Musteri = new HashSet<TBL_Musteri>();
        }
    
        public int KoltukID { get; set; }
        public string KoltukNO { get; set; }
        public Nullable<int> Class { get; set; }
        public Nullable<int> Durum { get; set; }
        public Nullable<decimal> Fiyat { get; set; }
    
        public virtual TBL_Class TBL_Class { get; set; }
        public virtual TBL_Durum TBL_Durum { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_Musteri> TBL_Musteri { get; set; }
    }
}
