//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThyBilet.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_UcusUrun
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBL_UcusUrun()
        {
            this.TBL_UrunGirdiCikti = new HashSet<TBL_UrunGirdiCikti>();
        }
    
        public int UrunID { get; set; }
        public string UrunAd { get; set; }
        public Nullable<int> UrunGrupAd { get; set; }
        public Nullable<decimal> Fiyat { get; set; }
        public Nullable<byte> Kdv { get; set; }
        public Nullable<decimal> Adet { get; set; }
        public Nullable<int> Durum { get; set; }
        public Nullable<int> Birim { get; set; }
    
        public virtual TBL_Birim TBL_Birim { get; set; }
        public virtual TBL_Durum TBL_Durum { get; set; }
        public virtual TBL_UcusUrunGrup TBL_UcusUrunGrup { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_UrunGirdiCikti> TBL_UrunGirdiCikti { get; set; }
    }
}
