//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThyBilet.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_Kasa
    {
        public int KasaID { get; set; }
        public string KasaAdi { get; set; }
        public Nullable<decimal> Bakiye { get; set; }
        public Nullable<decimal> Giren { get; set; }
        public Nullable<decimal> Cikan { get; set; }
        public Nullable<int> Durum { get; set; }
    
        public virtual TBL_Durum TBL_Durum { get; set; }
    }
}
